### MakeKmers.smk: Finding male-specific kmers in a Goby genome assembly
# ===========================================================================
# S. Lorena Ament-Velasquez
# 2025-03-19
# +++++++++++++++++++++++++++++++++++++++++++++++++

# Sample IDs
SampleIDs: ["PflaHELAf", "PflaKGBDf", "PflaHELEm", "PflaKGBHm"]
# Illumina reads path
path2BAMs:  "../5_GobyIlluCoverage/mapping" # there should be a folder per sample, and inside a BAM file called "{sample}.sorted.debup.filtered.bam"
# The reference genome (absolute path)
REFGenome: "../../Dryad/Assembly/fGobFla1.fasta"
# The focal scaffold names
targetscfs: ["OZ251424", "OZ251425", "OZ251426"]
# SD scaffold
SDscfs: ["OZ251425"]
# satDNA gff
satDNA: "../data/Annotation/fGobFla1-GobyTideCluster_v1.00.gff3"
# TE gff
TEgff: "../data/Annotation/fGobFla1-GobyTEv1.00.gff3"
# Population file (a headerless, tab-separated file)
popfile: "data/popfile.txt"
# Pixy window size
WINSIZE: 50000
# Ploting script
PixyGobySD: "scripts/PixyGobySDFrench.R"
